#! /bin/sh

#libinput-gestures daemon for gesture input
libinput-gestures-setup start &

#pkill plank && sleep 2 && plank &

# source the colors. from pywal
#. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

if ([ $(xrandr --listactivemonitors | grep -v "Monitors" | cut -d " " -f4 | cut -d"+" -f2 | uniq | wc -l) -eq 1 ]); then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7
else
    bspc monitor HDMI1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9
fi

bspc config border_width         3
bspc config window_gap           5

sleep 2 && bspc config top_padding 35 &

# Bar
pkill polybar &
~/.config/polybar/launch.sh &

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# >> Mis. Rules

#bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Nitrogen state=floating rectangle=640x360+2760+1040
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+2760+1040
bspc rule -a Plank layer=above manage=on border=off
# Border

# Set the border colors.

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "ffad00"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config focused_border_color        "#ffad00"
bspc config normal_border_color         "#33302f"
bspc config active_border_color         "#fbb86c"

#
# Autostart
#
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &

# Notifications
/usr/bin/dunst &
# pkill deadd-notificat && sleep 2 && deadd-notification-center &


# Polkit
killall firewall-applet

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring-daemon --start --components=secrets &
#/usr/lib/polkit-1/polkit-agent-helper-1 &

# Wallpaper
nitrogen --restore &
wal -i "$(grep -m1 'file=' ~/.config/nitrogen/bg-saved.cfg | sed 's/file=//' | xargs echo -n)" -n &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
picom --experimental-backends -b &
#picom -CGb &
# Network Applet
nm-applet --indicator &
# pkill firewall-applet && sleep 2 && firewall-applet &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &
